version: "3" # optional since v1.27.0

services:
  sqlserver:
    container_name: sqlserver
    hostname: sqlserver_host
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12!
    volumes:
      - ./sqlvolume/data:/var/opt/mssql/data:rw
      - ./sqlvolume/log:/var/opt/mssql/log:rw
      - ./sqlvolume/secrets:/var/opt/mssql/secrets:rw
